### ISSUE TITLE
child_process环境执行时报错

### ISSUE THREAD

**Issue by FocusCare** [jinphen/upyun_cdn#1]
util.js 中process.stdout在child_process下为null

**Comment by jinphen** [comment]
这个问题是由于在child_preocess下，process.stdout不是TTY，所以没有clearLine和cursorTo这两个方法。
能说说你这个使用的场景么？

**Comment by FocusCare** [comment]
使用child_process的exec调用命令

**Comment by jinphen** [comment]
这个可以修改掉，但一些上传打印的数据使用child_process就不好取到了。
